{% set version = "3.2.6" %}

package:
  name: rpy2
  version: {{version}}

source:
  hg_url: https://bitbucket.org/rpy2/rpy2
  hg_tag: {{version}}
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0
  run:
    - python
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0

test:
  source_files:
    - rpy2/tests
  requires:
    - r-survival
    - r-ggplot2 >=2.2.1
    - ipython
    - numpy
    - pandas
    - pytest
  imports:
    - rpy2
    - rpy2.rlike
    - rpy2.ipython
    - rpy2.rinterface
    - rpy2.robjects
    - rpy2.robjects.lib
  commands:
    - pytest -s -rxs -v rpy2/tests

about:
  home: https://rpy2.bitbucket.io/
  license: GPL-2.0
  license_family: GPL
  summary: "Python interface to the R language (embedded R)"
